import logging
import stat
from typing import List, Optional
from uuid import UUID
from sqlalchemy import insert
from sqlalchemy.orm import joinedload

from core.processors.embedding_processor import EmbeddingProcessor
from core.processors.post_processor import PostProcessor
from fastapi import HTTPException
from fastapi.encoders import jsonable_encoder
from models.all import Embedding, Post, PostEdit, post_tags, Tag, UserPostEvent
from models.db import get_db
from models.schemas.course_schema import CourseTagInformation, CourseTagsResponse
from models.schemas.general_schema import GeneralResponse
from models.schemas.post_schema import (
    CreatePostEditRequest,
    CreatePostRequest,
    GetPostResponse,
    PostEditResponse,
    PostEmbeddingMetadata,
    PostResponse,
)

logger = logging.getLogger(__name__)


def create_post(user_id: str, c_id: str, post_info: CreatePostRequest) -> Post:
    with get_db() as db:
        post = Post(
            title=post_info.title,
            course_id=c_id,
            content=post_info.content,
            created_by=user_id,
            # local_id will be auto-generated by the database trigger
        )
        try:
            db.add(post)
            db.flush()
            db.refresh(post)
            return post
        except Exception as e:
            raise e


def get_posts(c_id: str) -> List[Post]:
    try:
        with get_db() as db:
            posts = (
                db.query(Post)
                .filter(Post.course_id == c_id)
                .order_by(Post.applied_at.desc())
                .all()
            )
            return posts
    except Exception as e:
        print(f"Error in get_posts: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch posts: {str(e)}")


def get_post(user_id: str, c_id: str, local_id: int) -> GetPostResponse:
    try:
        with get_db() as db:
            post: Post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )

            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            stats = getMetadata(db, post.id)
            user_interactions = getUserInteractions(db, user_id, post.id)

            post_response = PostResponse(
                title=post.title,
                content=post.content,
                created_by=post.created_by,
                id=post.id,
                local_id=post.local_id,
                course_id=post.course_id,
                status=post.status,
            )

            return GetPostResponse(
                post=post_response, stats=stats, user_interactions=user_interactions
            )
    except Exception as e:
        print(f"Error in get_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch posts: {str(e)}")


def update_post(
    c_id: str, user_id: str, local_id: int, post_edit_info: CreatePostEditRequest
) -> PostEditResponse:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )

            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            post.content = post_edit_info.new_content

            # Create embedding in the Embeddings table if needed
            # embedding_processor = EmbeddingProcessor()
            # embedding = Embedding(
            #     entity_type="post",
            #     entity_id=post.id,
            #     content=post_edit_info.new_content,
            #     embedding=embedding_processor.generate_embedding(post_edit_info.new_content)
            # )
            # db.add(embedding)

            post_edit = PostEdit(
                post_id=post.id,  # Using UUID
                edited_by=user_id,
                new_content=post_edit_info.new_content,
                edit_reason=post_edit_info.edit_reason,
            )

            db.add(post_edit)
            db.flush()

            return PostEditResponse(
                id=post_edit.id,
                edited_by=UUID(user_id),
                new_content=post_edit_info.new_content,
                edit_reason=post_edit_info.edit_reason,
                post_id=post.id,  # Added post_id to response
            )
    except HTTPException as e:
        raise
    except Exception as e:
        print(f"Error in update_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to update post: {str(e)}")


def delete_post(c_id: str, user_id: str, local_id: int) -> Post:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            db.delete(post)
            db.flush()
            return post
    except Exception as e:
        print(f"Error in delete_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to delete post: {str(e)}")


def view_post(c_id: str, user_id: str, local_id: int) -> UserPostEvent:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            post_event = (
                db.query(UserPostEvent)
                .filter(
                    UserPostEvent.post_id == post.id, UserPostEvent.user_id == user_id
                )
                .first()
            )

            if post_event:
                return post_event

            event = UserPostEvent(
                viewed=True, liked=False, user_id=user_id, post_id=post.id
            )
            db.add(event)
            db.flush()
            return event
    except Exception as e:
        print(f"Error in view_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to record view: {str(e)}")


def like_post(c_id: str, user_id: str, local_id: int) -> UserPostEvent:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            post_event = (
                db.query(UserPostEvent)
                .filter(
                    UserPostEvent.post_id == post.id, UserPostEvent.user_id == user_id
                )
                .first()
            )

            if not post_event:
                event = UserPostEvent(
                    viewed=True, liked=True, user_id=user_id, post_id=post.id
                )
                db.add(event)
                db.flush()
                return event
            else:
                post_event.liked = not post_event.liked
                db.flush()
                return post_event
    except Exception as e:
        print(f"Error in like_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to toggle like: {str(e)}")


def getMetadata(db, post_id: UUID):
    numLikes = db.query(UserPostEvent).filter_by(post_id=post_id, liked=True).count()
    numViews = db.query(UserPostEvent).filter_by(post_id=post_id, viewed=True).count()
    return {"views": numViews, "likes": numLikes}


def getUserInteractions(db, user_id: str, post_id: UUID):
    user_interaction = (
        db.query(UserPostEvent).filter_by(post_id=post_id, user_id=user_id).first()
    )

    if not user_interaction:
        return {"viewed": False, "liked": False}

    return {"viewed": user_interaction.viewed, "liked": user_interaction.liked}


def update_embeddings(c_id: str, user_id: str, local_id: int) -> GeneralResponse:
    """Update embeddings for a post."""
    try:
        with get_db() as db:
            # First get the post
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )

            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            # Initialize post processor and process embeddings
            with PostProcessor(db) as processor:
                processor.process_post(post.id)

            return GeneralResponse(msg="Post embeddings updated successfully")

    except HTTPException as e:
        raise
    except Exception as e:
        logger.error(
            "Error updating post embeddings",
            extra={"course_id": c_id, "local_id": local_id, "error": str(e)},
            exc_info=True,
        )
        raise HTTPException(
            status_code=500, detail=f"Failed to update post embeddings: {str(e)}"
        )


def get_embedding_metadata(
    c_id: str, user_id: str, local_id: int
) -> PostEmbeddingMetadata:
    """Get metadata about a post's embeddings."""
    try:
        with get_db() as db:
            # First get the post
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )

            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            # Get the embeddings for this post
            embeddings = (
                db.query(Embedding)
                .filter(Embedding.entity_type == "post", Embedding.entity_id == post.id)
                .order_by(Embedding.created_at.desc())
                .all()
            )

            if not embeddings:
                return PostEmbeddingMetadata()  # Returns with default values

            return PostEmbeddingMetadata(
                last_updated=embeddings[0].created_at,
                chunk_count=len(embeddings),
                has_embeddings=True,
            )

    except HTTPException as e:
        raise
    except Exception as e:
        logger.error(
            "Error getting post embedding metadata",
            extra={"course_id": c_id, "local_id": local_id, "error": str(e)},
            exc_info=True,
        )
        raise HTTPException(
            status_code=500, detail=f"Failed to get post embedding metadata: {str(e)}"
        )


def get_post_tags(post_id: str) -> CourseTagsResponse:
    with get_db() as db:
        post = (
            db.query(Post)
            .options(joinedload(Post.tags))
            .filter(Post.id == UUID(post_id))
            .first()
        )
        if not post:
            raise HTTPException(status_code=404, detail="Post not found")
        tags = []
        for tag in post.tags:
            tags.append(
                CourseTagInformation(
                    id=tag.id,
                    name=tag.name,
                    visibility=tag.visibility,
                    course_id=tag.course_id,
                    parent_tag_id=tag.parent_tag_id,
                    created_by=tag.created_by,
                    properties=tag.properties,
                )
            )
    return CourseTagsResponse(tags=tags)


def add_post_tag(post_id: str, tag_id: str, author_id: str) -> GeneralResponse:
    with get_db() as db:
        try:
            post = db.query(Post).filter(Post.id == UUID(post_id)).first()
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            tag = db.query(Tag).filter(Tag.id == UUID(tag_id)).first()
            if not tag:
                raise HTTPException(status_code=404, detail="Tag not found")
            exec = insert(post_tags).values(
                post_id=post.id, tag_id=tag.id, created_by=UUID(author_id)
            )
            db.execute(exec)
            db.commit()
        except Exception as e:
            db.rollback()
            raise HTTPException(
                status_code=500, detail=f"Failed to assign tag to post: {str(e)}"
            )

    return GeneralResponse(msg="Tag assigned to post successfully")


def remove_post_tag(post_id: str, tag_id: str) -> GeneralResponse:
    with get_db() as db:
        try:
            post = db.query(Post).filter(Post.id == UUID(post_id)).first()
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            tag = db.query(Tag).filter(Tag.id == UUID(tag_id)).first()
            if not tag:
                raise HTTPException(status_code=404, detail="Tag not found")

            post.tags.remove(tag)
            db.commit()
        except Exception as e:
            db.rollback()
            raise HTTPException(
                status_code=500, detail=f"Failed to unassign tag from post: {str(e)}"
            )

    return GeneralResponse(msg="Tag unassigned from post successfully")
