import stat
from typing import List, Optional
from uuid import UUID

import logging

from core.processors.embedding_processor import EmbeddingProcessor
from fastapi import HTTPException
from fastapi.encoders import jsonable_encoder
from core.processors.post_processor import PostProcessor
from models.all import Post, PostEdit, Profile, UserPostEvent
from models.db import get_db
from models.schemas.general_schema import GeneralResponse
from models.schemas.post_schema import (CreatePostEditRequest,
                                        CreatePostRequest, GetPostResponse,
                                        PostEditResponse, PostResponse)

logger = logging.getLogger(__name__)


def create_post(user_id: str, c_id: str, post_info: CreatePostRequest) -> Post:
    with get_db() as db:
        post = Post(
            title=post_info.title,
            course_id=c_id,
            content=post_info.content,
            created_by=user_id,
            # local_id will be auto-generated by the database trigger
        )
        try:
            db.add(post)
            db.flush()
            db.refresh(post)
            return post
        except Exception as e:
            raise e


def get_posts(c_id: str) -> List[Post]:
    try:
        with get_db() as db:
            posts = (
                db.query(Post)
                .filter(Post.course_id == c_id)
                .order_by(Post.applied_at.desc())
                .all()
            )
            return posts
    except Exception as e:
        print(f"Error in get_posts: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch posts: {str(e)}")


def get_post(user_id: str, c_id: str, local_id: int) -> GetPostResponse:
    try:
        with get_db() as db:
            post: Post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )

            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            stats = getMetadata(db, post.id)
            user_interactions = getUserInteractions(db, user_id, post.id)

            post_response = PostResponse(
                title=post.title,
                content=post.content,
                created_by=post.created_by,
                id=post.id,
                local_id=post.local_id,
                course_id=post.course_id,
                status=post.status,
            )

            return GetPostResponse(
                post=post_response, stats=stats, user_interactions=user_interactions
            )
    except Exception as e:
        print(f"Error in get_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch posts: {str(e)}")


def update_post(
    c_id: str, user_id: str, local_id: int, post_edit_info: CreatePostEditRequest
) -> PostEditResponse:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )

            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            post.content = post_edit_info.new_content

            # Create embedding in the Embeddings table if needed
            # embedding_processor = EmbeddingProcessor()
            # embedding = Embedding(
            #     entity_type="post",
            #     entity_id=post.id,
            #     content=post_edit_info.new_content,
            #     embedding=embedding_processor.generate_embedding(post_edit_info.new_content)
            # )
            # db.add(embedding)

            post_edit = PostEdit(
                post_id=post.id,  # Using UUID
                edited_by=user_id,
                new_content=post_edit_info.new_content,
                edit_reason=post_edit_info.edit_reason,
            )

            db.add(post_edit)
            db.flush()
            
            return PostEditResponse(
                id=post_edit.id,
                edited_by=UUID(user_id),
                new_content=post_edit_info.new_content,
                edit_reason=post_edit_info.edit_reason,
                post_id=post.id,  # Added post_id to response
            )
    except HTTPException as e:
        raise
    except Exception as e:
        print(f"Error in update_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to update post: {str(e)}")


def delete_post(c_id: str, user_id: str, local_id: int) -> Post:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            db.delete(post)
            db.flush()
            return post
    except Exception as e:
        print(f"Error in delete_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to delete post: {str(e)}")


def view_post(c_id: str, user_id: str, local_id: int) -> UserPostEvent:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")
                
            post_event = (
                db.query(UserPostEvent)
                .filter(
                    UserPostEvent.post_id == post.id, UserPostEvent.user_id == user_id
                )
                .first()
            )

            if post_event:
                return post_event

            event = UserPostEvent(
                viewed=True, liked=False, user_id=user_id, post_id=post.id
            )
            db.add(event)
            db.flush()
            return event
    except Exception as e:
        print(f"Error in view_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to record view: {str(e)}")


def like_post(c_id: str, user_id: str, local_id: int) -> UserPostEvent:
    try:
        with get_db() as db:
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")
                
            post_event = (
                db.query(UserPostEvent)
                .filter(
                    UserPostEvent.post_id == post.id, UserPostEvent.user_id == user_id
                )
                .first()
            )

            if not post_event:
                event = UserPostEvent(
                    viewed=True, liked=True, user_id=user_id, post_id=post.id
                )
                db.add(event)
                db.flush()
                return event
            else:
                post_event.liked = not post_event.liked
                db.flush()
                return post_event
    except Exception as e:
        print(f"Error in like_post: {type(e).__name__}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to toggle like: {str(e)}")


def getMetadata(db, post_id: UUID):
    numLikes = db.query(UserPostEvent).filter_by(post_id=post_id, liked=True).count()
    numViews = db.query(UserPostEvent).filter_by(post_id=post_id, viewed=True).count()
    return {"views": numViews, "likes": numLikes}


def getUserInteractions(db, user_id: str, post_id: UUID):
    user_interaction = (
        db.query(UserPostEvent).filter_by(post_id=post_id, user_id=user_id).first()
    )

    if not user_interaction:
        return {"viewed": False, "liked": False}

    return {"viewed": user_interaction.viewed, "liked": user_interaction.liked}


def update_embeddings(c_id: str, user_id: str, local_id: int) -> GeneralResponse:
    """Update embeddings for a post."""
    try:
        with get_db() as db:
            # First get the post
            post = (
                db.query(Post)
                .filter(Post.course_id == c_id, Post.local_id == local_id)
                .first()
            )
            
            if not post:
                raise HTTPException(status_code=404, detail="Post not found")

            # Initialize post processor and process embeddings
            with PostProcessor(db) as processor:
                processor.process_post(post.id)

            return GeneralResponse(msg="Post embeddings updated successfully")

    except HTTPException as e:
        raise
    except Exception as e:
        logger.error(
            "Error updating post embeddings",
            extra={
                "course_id": c_id,
                "local_id": local_id,
                "error": str(e)
            },
            exc_info=True
        )
        raise HTTPException(
            status_code=500,
            detail=f"Failed to update post embeddings: {str(e)}"
        )