"""create_job_and_job_specification

Revision ID: 0f36437bdda7
Revises: cec36a0a76fd
Create Date: 2025-01-25 13:12:49.373856

"""
from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f36437bdda7'
down_revision: Union[str, None] = 'cec36a0a76fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('not started', 'running', 'success', 'failed', name='job_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='job_priority'), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_interval', sa.Integer(), nullable=False),
    sa.Column('recurring_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('job_specification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_name', sa.Text(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('failure_strategy', sa.Enum('retry', 'abort', name='job_failure_strategy'), nullable=False),
    sa.Column('cleanup_action', sa.Text(), nullable=True),
    sa.Column('job_file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['public.job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_specification', schema='public')
    op.drop_table('job', schema='public')
    # ### end Alembic commands ###
