"""create_job_and_job_specification

Revision ID: 0f36437bdda7
Revises: cec36a0a76fd
Create Date: 2025-01-25 13:12:49.373856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f36437bdda7'
down_revision: Union[str, None] = 'cec36a0a76fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('not startedrunning', 'success', 'failed', name='job_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='job_priority'), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_interval', sa.Integer(), nullable=True),
    sa.Column('recurring_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('jobs_specification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_name', sa.Text(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('failure_strategy', sa.Enum('retry', 'abort', name='job_failure_strategy'), nullable=False),
    sa.Column('cleanup_action', sa.Text(), nullable=True),
    sa.Column('job_file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['public.jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_foreign_key(None, 'chunk_relations', 'chunks', ['target_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunk_relations', 'chunks', ['source_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'chunks', ['parent_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'post_edits', 'profiles', ['edited_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'post_edits', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'profiles', 'users', ['id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.alter_column('posts', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunk_relations', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunk_relations', schema='public', type_='foreignkey')
    op.drop_table('jobs_specification', schema='public')
    op.drop_table('jobs', schema='public')
    # ### end Alembic commands ###
