"""Add like and view count to posts

Revision ID: 1563ceca7cd9
Revises: d946f44ab9b8
Create Date: 2025-02-08 12:16:39.097518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1563ceca7cd9'
down_revision: Union[str, None] = 'd946f44ab9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("view_count", sa.Integer(), nullable=True, server_default=sa.text("0")), schema="public"
    )
    op.add_column(
        "posts", sa.Column("like_count", sa.Integer(), nullable=True, server_default=sa.text("0")), schema="public"
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "view_count", schema="public")
    op.drop_column("posts", "like_count", schema="public")

    pass
    # ### end Alembic commands ###
