"""tags db, roles commented out

Revision ID: 57f694383a69
Revises: cec36a0a76fd
Create Date: 2025-01-28 10:32:14.365514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f694383a69'
down_revision: Union[str, None] = 'cec36a0a76fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Self', 'Others', name='permissiontypeenum'), nullable=False),
    sa.Column('access', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='visibilityenum'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('parent_tag_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['public.courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['public.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_foreign_key(None, 'chunk_relations', 'chunks', ['target_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunk_relations', 'chunks', ['source_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'chunks', ['parent_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'post_edits', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'post_edits', 'profiles', ['edited_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'profiles', 'users', ['id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_post_events', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunk_relations', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunk_relations', schema='public', type_='foreignkey')
    op.drop_table('tags', schema='public')
    op.drop_table('permissions', schema='public')
    # ### end Alembic commands ###
