"""empty message

Revision ID: 7a062c24ebe7
Revises: 6af8e5b591f2
Create Date: 2025-01-31 12:50:00.612964

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a062c24ebe7"
down_revision: Union[str, None] = "6af8e5b591f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "status",
        existing_type=postgresql.ENUM(
            "draft", "published", "archived", "deleted", name="post_status"
        ),
        type_=sa.Enum(
            "DRAFT",
            "PUBLISHED",
            "ARCHIVED",
            "DELETED",
            name="post_status",
            schema="public",
        ),
        existing_nullable=True,
    )
    op.create_unique_constraint(
        "uq_courses_group_code_section",
        "courses",
        ["c_group", "code", "section"],
        schema="public",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_courses_group_code_section", "courses", schema="public", type_="unique"
    )
    op.alter_column(
        "posts",
        "status",
        existing_type=sa.Enum(
            "DRAFT",
            "PUBLISHED",
            "ARCHIVED",
            "DELETED",
            name="post_status",
            schema="public",
        ),
        type_=postgresql.ENUM(
            "draft", "published", "archived", "deleted", name="post_status"
        ),
        existing_nullable=True,
    )

    # ### end Alembic commands ###
