"""added_document_tags_and_post_tags

Revision ID: 7efc85ef32eb
Revises: 57f694383a69
Create Date: 2025-01-30 23:23:34.194059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7efc85ef32eb'
down_revision: Union[str, None] = '57f694383a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tags',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doc_id'], ['public.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['public.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', 'tag_id'),
    schema='public'
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['public.posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['public.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id'),
    schema='public'
    )
    op.create_foreign_key(None, 'course_documents', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'embeddings', 'embeddings', ['parent_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'post_edits', 'profiles', ['edited_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'post_edits', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('posts', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('posts', 'status',
               existing_type=postgresql.ENUM('active', 'deleted', name='poststatus'),
               type_=sa.Enum('public', 'private', name='poststatus', schema='public'),
               existing_nullable=True)
    op.create_foreign_key(None, 'posts', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'profiles', 'users', ['id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'query_history', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'query_history', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags', 'tags', ['parent_tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='auth', ondelete='SET NULL')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tags', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tags', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tags', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'query_history', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'query_history', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.alter_column('posts', 'status',
               existing_type=sa.Enum('public', 'private', name='poststatus', schema='public'),
               type_=postgresql.ENUM('active', 'deleted', name='poststatus'),
               existing_nullable=True)
    op.alter_column('posts', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'embeddings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_table('post_tags', schema='public')
    op.drop_table('document_tags', schema='public')
    # ### end Alembic commands ###
