"""update course profile relationship 4

Revision ID: 80cd76bd37dc
Revises: d6c7bcb7182c
Create Date: 2024-12-04 21:13:34.817866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80cd76bd37dc"
down_revision: Union[str, None] = "d6c7bcb7182c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey") # type: ignore
    # ### end Alembic commands ###
