"""edits to document ddl

Revision ID: 850aad04a7b8
Revises: 89e52911471d
Create Date: 2024-12-06 00:36:31.185191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "850aad04a7b8"
down_revision: Union[str, None] = "89e52911471d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "chunk_relations",
        "chunks",
        ["source_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "chunk_relations",
        "chunks",
        ["target_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "chunks",
        "chunks",
        ["parent_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "chunks",
        "documents",
        ["document_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "documents",
        ["document_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.add_column("documents", sa.Column("created_by", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None,
        "documents",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "profiles",
        ["edited_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "documents", schema="public", type_="foreignkey") # type: ignore
    op.drop_column("documents", "created_by")
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "chunks", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "chunks", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "chunk_relations", schema="public", type_="foreignkey") # type: ignore
    op.drop_constraint(None, "chunk_relations", schema="public", type_="foreignkey") # type: ignore
    # ### end Alembic commands ###
