"""embedding ddl

Revision ID: 89e52911471d
Revises: 3ee193ad8cce
Create Date: 2024-12-05 23:13:50.210752

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "89e52911471d"
down_revision: Union[str, None] = "3ee193ad8cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sa.String(length=50), nullable=True),
        sa.Column(
            "chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),  # type: ignore
            nullable=True,
        ),
        sa.Column("parent_chunk_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_type IN ('text', 'image', 'code')", name="valid_chunk_type"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(chunk_metadata) = 'object'", name="valid_metadata"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["public.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id"], ["public.chunks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        "chunks_embedding_idx",
        "chunks",
        ["embedding"],
        unique=False,
        schema="public",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "chunk_relations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("source_chunk_id", sa.UUID(), nullable=False),
        sa.Column("target_chunk_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(properties) = 'object'", name="valid_metadata"
        ),
        sa.CheckConstraint(
            "relation_type IN ('contains', 'references', 'similar_to', 'continuation_of')",
            name="valid_relation_type",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"], ["public.chunks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_chunk_id"], ["public.chunks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "documents",
        ["document_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "profiles",
        ["edited_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "posts",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")  # type: ignore
    op.drop_table("chunk_relations", schema="public")
    op.drop_index(
        "chunks_embedding_idx",
        table_name="chunks",
        schema="public",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chunks", schema="public")
    # ### end Alembic commands ###
