"""Add messsages, channels and user_channels tables

Revision ID: aa0a89d4c13e
Revises: cec36a0a76fd
Create Date: 2025-01-26 14:55:55.654009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'aa0a89d4c13e'
down_revision: Union[str, None] = 'cec36a0a76fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('user_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['public.channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_foreign_key(None, 'chunk_relations', 'chunks', ['source_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunk_relations', 'chunks', ['target_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'chunks', ['parent_chunk_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'documents', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'course_documents', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'post_edits', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'post_edits', 'profiles', ['edited_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'profiles', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'profiles', 'users', ['id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_events', 'profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_post_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'post_edits', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'course_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunk_relations', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chunk_relations', schema='public', type_='foreignkey')
    op.drop_table('user_channels', schema='public')
    op.drop_table('messages', schema='public')
    op.drop_table('channels', schema='public')
    # ### end Alembic commands ###
