"""user management tables

Revision ID: bff88f42f7fd
Revises: d946f44ab9b8
Create Date: 2025-02-05 23:13:21.847148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'bff88f42f7fd'
down_revision: Union[str, None] = 'd946f44ab9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'invites',
        existing_comment='Table for invitation information',
        schema=None
    )
    op.drop_table_comment(
        'super_users',
        existing_comment='Users who can invite and approve invitations',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'super_users',
        'Users who can invite and approve invitations',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'invites',
        'Table for invitation information',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
