"""Change post id's from UUID to integer

Revision ID: cec36a0a76fd
Revises: b74848df0c5e
Create Date: 2025-01-08 12:50:50.388107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "cec36a0a76fd"
down_revision: Union[str, None] = "b74848df0c5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "posts", sa.Column("id_temp", sa.Integer(), autoincrement=True, nullable=True)
    )
    op.add_column("post_edits", sa.Column("post_id_int", sa.Integer(), nullable=True))
    op.add_column(
        "user_post_events", sa.Column("post_id_int", sa.Integer(), nullable=True)
    )

    connection = op.get_bind()
    meta = sa.MetaData()
    meta.reflect(bind=connection)
    posts_table = meta.tables["posts"]
    post_edits_table = meta.tables["post_edits"]
    user_post_events_table = meta.tables["user_post_events"]

    rows = connection.execute(posts_table.select()).fetchall()

    uuid_to_int_map = {row._mapping["id"]: index + 1 for index, row in enumerate(rows)}

    for uuid, new_id in uuid_to_int_map.items():
        connection.execute(
            posts_table.update().where(posts_table.c.id == uuid).values(id_temp=new_id)
        )

    for table, old_column, new_column in [
        (post_edits_table, "post_id", "post_id_int"),
        (user_post_events_table, "post_id", "post_id_int"),
    ]:
        rows = connection.execute(table.select()).fetchall()
        for row in rows:
            row_dict = row._mapping
            old_post_id = row_dict["post_id"]
            if old_post_id in uuid_to_int_map:
                new_post_id = uuid_to_int_map[old_post_id]
                connection.execute(
                    table.update()
                    .where(table.c[old_column] == old_post_id)
                    .values({new_column: new_post_id})
                )

    op.drop_column("post_edits", "post_id")
    op.drop_column("user_post_events", "post_id")

    op.alter_column("posts", "id_temp", nullable=False)

    op.execute("ALTER TABLE posts DROP CONSTRAINT posts_pkey CASCADE")
    op.drop_column("posts", "id")
    op.alter_column("posts", "id_temp", new_column_name="id")
    op.create_primary_key("posts_pkey", "posts", ["id"])

    op.alter_column(
        "post_edits", "post_id_int", new_column_name="post_id", nullable=False
    )
    op.alter_column(
        "user_post_events", "post_id_int", new_column_name="post_id", nullable=False
    )

    op.create_foreign_key(
        None, "user_post_events", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "post_edits", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )

    op.execute("CREATE SEQUENCE IF NOT EXISTS posts_id_seq START 1;")
    op.execute("ALTER TABLE posts ALTER COLUMN id SET DEFAULT nextval('posts_id_seq');")
    op.execute("SELECT setval('posts_id_seq', (SELECT MAX(id) FROM posts));")

    op.create_foreign_key(
        None,
        "chunk_relations",
        "chunks",
        ["target_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "chunk_relations",
        "chunks",
        ["source_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "chunks",
        "chunks",
        ["parent_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "chunks",
        "documents",
        ["document_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "documents",
        ["document_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "documents",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "profiles",
        ["edited_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post_edits", type_="foreignkey", schema="public")  # type: ignore
    op.drop_constraint(None, "user_post_events", type_="foreignkey", schema="public")  # type: ignore

    op.execute("ALTER TABLE posts DROP CONSTRAINT posts_pkey CASCADE")

    op.drop_column("posts", "id")

    op.add_column(
        "posts",
        sa.Column(
            "id", sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()")
        ),
    )

    op.drop_column("post_edits", "post_id", schema="public")
    op.drop_column("user_post_events", "post_id", schema="public")

    op.add_column("post_edits", sa.Column("post_id", sa.UUID(), nullable=False))
    op.add_column("user_post_events", sa.Column("post_id", sa.UUID(), nullable=False))

    op.create_primary_key("posts_pkey", "posts", ["id"])

    op.create_foreign_key(
        None,
        "post_edits",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
        source_schema="public",
        referent_schema="public",
    )

    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "documents", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "chunks", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "chunks", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "chunk_relations", schema="public", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "chunk_relations", schema="public", type_="foreignkey")  # type: ignore
    # ### end Alembic commands ###
