"""update course profile relationship 3

Revision ID: d6c7bcb7182c
Revises: a80ef9b1bb00
Create Date: 2024-12-04 21:11:53.283392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6c7bcb7182c"
down_revision: Union[str, None] = "a80ef9b1bb00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey")
    # ### end Alembic commands ###
