"""Posts

Revision ID: f25589834010
Revises: 80cd76bd37dc
Create Date: 2024-12-04 22:23:18.324193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f25589834010"
down_revision: Union[str, None] = "80cd76bd37dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "post_edits",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "profiles",
        ["edited_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "posts",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey")
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")
    # ### end Alembic commands ###
