"""consolidate_embeddings_update

Revision ID: f462eb503bac
Revises: fb29c383b6d1
Create Date: 2025-01-25 21:17:13.805576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "f462eb503bac"
down_revision: Union[str, None] = "fb29c383b6d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "course_documents",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "course_documents",
        "documents",
        ["document_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "documents",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_embeddings_entity",
        "embeddings",
        ["entity_type", "entity_id"],
        unique=False,
        schema="public",
    )
    op.create_foreign_key(
        None,
        "embeddings",
        "embeddings",
        ["parent_chunk_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "post_edits",
        "profiles",
        ["edited_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "posts",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "posts",
        "profiles",
        ["created_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "profiles",
        "users",
        ["id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_courses",
        "courses",
        ["course_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "profiles",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "user_post_events",
        "posts",
        ["post_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_post_events", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")
    op.drop_constraint(None, "user_courses", schema="public", type_="foreignkey")
    op.drop_constraint(None, "profiles", schema="public", type_="foreignkey")
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")
    op.drop_constraint(None, "posts", schema="public", type_="foreignkey")
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")
    op.drop_constraint(None, "post_edits", schema="public", type_="foreignkey")
    op.drop_constraint(None, "embeddings", schema="public", type_="foreignkey")
    op.drop_index("ix_embeddings_entity", table_name="embeddings", schema="public")
    op.drop_constraint(None, "documents", schema="public", type_="foreignkey")
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")
    op.drop_constraint(None, "course_documents", schema="public", type_="foreignkey")
    # ### end Alembic commands ###
