name: Lint Frontend

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        working-directory: frontend/

      - name: Lint code
        run: yarn lint
        working-directory: frontend/