name: Prettier Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          version: latest

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier check
        run: |
          npm prettier --check
